version: "3.8"

services:
  db:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sqlserver
    environment:
      - SA_PASSWORD=MyStrongPass123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - studentdbdata:/var/opt/mssql # Corrected volume mount target
    networks:
      - mynetwork

  api:
    build: .
    container_name: student_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=StudentDb;User Id=SA;Password=MyStrongPass123;Encrypt=False;
    ports:
      - "5002:8080"
    depends_on:
      - db
    networks:
      - mynetwork

volumes:
  studentdbdata:
    driver: local # Ensure the volume is defined as a mapping with a driver (optional but recommended)

networks:
  mynetwork:
    driver: bridge
