name: CI Pipeline

# Run the pipeline on the self-hosted runner
on:
  push:
    paths:
      - 'code/**' # Trigger only when changes are made in the code directory
  workflow_dispatch: # Manual trigger option

jobs:
  build:
    runs-on: self-hosted # Use the self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Stage 1: Build API
      - name: Build API
        run: make build # Ensure you have a 'build' target in your Makefile

      # Stage 2: Run tests
      - name: Run tests
        run: make test # Ensure you have a 'test' target in your Makefile

      # Stage 3: Perform code linting
      - name: Code linting
        run: make lint # Ensure you have a 'lint' target in your Makefile

      # Stage 4: Docker login
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Stage 5: Docker build and push
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest
